feat: updated

diff --git a/.github/actions/get-feature-flag-bucket/action.yml b/.github/actions/get-feature-flag-bucket/action.yml
--- a/.github/actions/get-feature-flag-bucket/action.yml
+++ b/.github/actions/get-feature-flag-bucket/action.yml
@@ -24,35 +24,47 @@ runs:
         BASE_REF: ${{ github.base_ref }}
         REF_NAME: ${{ github.ref_name }}
       run: |
+        # Will have inputs.ref in selected cases, head_ref in PR branches with a base,
+        # and ref_name in a base/main branch (like develop)
         git_ref="${{ inputs.ref || github.head_ref || github.ref_name }}"
-        PATTERN="(CP-[0-9]+)"
 
         branch_name=$(
           echo "${git_ref##*/}" |
           tr -cd 'a-zA-Z0-9-'
         )
+
+        # Abort if there's no stack name.
         if [[ -z "$branch_name" ]]; then
-          echo "Empty Branch Name"
-          exit 1
+          echo "Empty Stack Name" 
+          exit 1 
         fi
+
         echo "Branch Name: '$branch_name'"
+        echo "branch_name=$branch_name" >> "$GITHUB_OUTPUT"
 
-        if [[ $branch_name =~ $PATTERN ]]; then
-          jira_story="${BASH_REMATCH[1]}"
-          random_chars=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10)
-          feature_flag_s3_bucket="${jira_story}-feature-flag-s3-${random_chars}"
-          echo "feature_flag_s3_bucket=$feature_flag_s3_bucket"
-        else
-          echo "No JIRA story found in the branch name"
-          exit 1
-        fi
-
-        feature_flag_s3_bucket_slugified=$(
-          echo "$feature_flag_s3_bucket" | 
+        branch_name_slugified=$(
+          echo "$branch_name" | 
           tr '[:upper:]' '[:lower:]' | 
           tr -s '[:space:]' '-' | 
           tr -cd '[:alnum:]-' | 
           sed -E 's/-+$//'
         )
 
-        echo "feature_flag_s3_bucket_slugified=$feature_flag_s3_bucket_slugified" >> "$GITHUB_OUTPUT"
+        echo "Branch Name Slugified: '$branch_name_slugified'"
+        echo "branch_name_slugified=$branch_name_slugified" >> "$GITHUB_OUTPUT"
+
+        feature_flag_s3_bucket="${branch_name_slugified}-feature-flag-bucket"
+
+        # Check if the S3 bucket name exceeds 63 characters
+        if [[ ${#feature_flag_s3_bucket} -gt 63 ]]; then
+          echo "❌ Error: The generated feature flag S3 bucket name exceeds the 63-character limit."
+          echo "🔎 Current Branch Name: '$branch_name'"
+          echo "🪣 Generated Bucket Name: '$feature_flag_s3_bucket' (${#feature_flag_s3_bucket} characters)"
+          echo "⚠️  S3 bucket names must be 63 characters or fewer."
+          echo "💡 Action Required: Please shorten your branch name to ensure the bucket name stays within the limit."
+          echo "ℹ️  Note: The feature flag S3 bucket name is generated based solely on the branch name."
+          exit 1
+        fi
+
+        echo "Feature Flag S3 Bucket: '$feature_flag_s3_bucket'"
+        echo "feature_flag_s3_bucket=$feature_flag_s3_bucket" >> "$GITHUB_OUTPUT"
