testing codedeploy rollback

diff --git a/.github/workflows/codedeploy-stage.yml b/.github/workflows/codedeploy-stage.yml
--- a/.github/workflows/codedeploy-stage.yml
+++ b/.github/workflows/codedeploy-stage.yml
@@ -61,16 +61,43 @@ jobs:
       - name: Trigger release-dependent-codedeploy.yml
         id: trigger_workflow
         run: |
-          run_id=$(gh workflow run release-dependent-codedeploy.yml \
-            -f codedeploy_rollback=${{ env.codedeploy_rollback }} \
-            --json id -q '.id')
-          echo "run_id=${run_id}" >> $GITHUB_ENV
+          gh workflow run release-dependent-codedeploy.yml \
+          --field codedeploy_rollback=${{ env.codedeploy_rollback }}
 
+      - name: Get Workflow Run ID of release-dependent-codedeploy.yml workflow
+        id: get_run_id
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          max_attempts=5  # Maximum number of attempts to retrieve the workflow run ID
+          attempt=0
+          workflow_list=""
+
+          while [ -z "$workflow_list" ] && [ $attempt -lt $max_attempts ]; do
+            echo "Attempt $(($attempt+1)) to retrieve workflow run ID"
+            workflow_list=$(gh run list --workflow=maven.yml --limit=1 --json databaseId)
+            
+            if [ -z "$workflow_list" ]; then
+              echo "Workflow run ID not yet available. Retrying..."
+              attempt=$(($attempt + 1))
+              sleep 10  # Wait for a short time before retrying
+            else
+              echo "Workflow run ID retrieved successfully."
+            fi
+          done
+
+          if [ -z "$workflow_list" ]; then
+            echo "Failed to retrieve workflow run ID after $max_attempts attempts"
+            exit 1
+          fi
+
+          run_id=$(echo "$workflow_list" | jq -r '.[0].databaseId')
+          echo "run_id=$run_id" >> $GITHUB_ENV
 
       - name: Echo Run_ID
         run: echo "Run ID= ${{ env.run_id }}"
 
-      - name: Watch workflow run
+      - name: Watch workflow run of release-dependent-codedeploy.yml
         id: watch_workflow
         run: |
           gh run watch ${{ env.run_id }}
