feat: updated

diff --git a/.github/workflows/qa-automation.yml b/.github/workflows/qa-automation.yml
--- a/.github/workflows/qa-automation.yml
+++ b/.github/workflows/qa-automation.yml
@@ -18,7 +18,7 @@ jobs:
   qa_tests:
     runs-on: ubuntu-latest
     outputs:
-      job_status: ${{ steps.set_status.outputs.status }}
+      job_status: ${{ steps.check_status.outputs.status }}
     strategy:
       fail-fast: false
       matrix:
@@ -56,7 +56,7 @@ jobs:
               attempt=$((attempt + 1))
               sleep 10
             else
-              echo "Workflow run ID retrieved successfully. == $workflow_list"
+              echo "Workflow run ID retrieved successfully."
             fi
           done
 
@@ -83,6 +83,7 @@ jobs:
               echo "Final conclusion: $conclusion"
               if [ "$conclusion" != "success" ]; then
                 echo "status=failure" >> $GITHUB_OUTPUT
+                exit 1
               else
                 echo "status=success" >> $GITHUB_OUTPUT
               fi
@@ -90,16 +91,16 @@ jobs:
             sleep 15
           done
 
-  finalize_status:
-    needs: qa_tests
-    runs-on: ubuntu-latest
-    steps:
-      - name: Set final job status
-        id: set_status
-        run: |
-          if [ "${{ needs.qa_tests.result }}" == "success" ]; then
-            echo "status=success" >> $GITHUB_OUTPUT
-          else
-            echo "status=failure" >> $GITHUB_OUTPUT
-            exit 1
-          fi
+  # finalize_status:
+  #   needs: qa_tests
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Set final job status
+  #       id: set_status
+  #       run: |
+  #         if [ "${{ needs.qa_tests.result }}" == "success" ]; then
+  #           echo "status=success" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "status=failure" >> $GITHUB_OUTPUT
+  #           exit 1
+  #         fi
