testing qa-automation

diff --git a/.github/workflows/qa-automation-test.yml b/.github/workflows/qa-automation-test.yml
--- a/.github/workflows/qa-automation-test.yml
+++ b/.github/workflows/qa-automation-test.yml
@@ -1,16 +1,12 @@
 name: qa-automation
 
 on:
-  push:
+  workflow_run:
+    workflows: ["release-dependent-codedeploy"]
     branches:
       - multi_tenant_stage
-      - multi_tenant_dev
-  # workflow_run:
-  #   workflows: ["release-dependent-codedeploy"]
-  #   branches:
-  #     - multi_tenant_stage
-  #   types:
-  #     - completed
+    types:
+      - completed
 
 permissions:
   id-token: write 
@@ -20,84 +16,84 @@ permissions:
   actions: read
 
 jobs:
-  # qa-tests:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
+  qa-tests:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-  #     - name: Run maven.yml workflow in qa-automation repository
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-  #       run: |
-  #         gh workflow run maven.yml --repo prashant-cloudbolt/qa-automation
+      - name: Run maven.yml workflow in qa-automation repository
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          gh workflow run maven.yml --repo prashant-cloudbolt/qa-automation
 
-  #     - name: Get Workflow Run ID of maven.yml workflow
-  #       id: get_run_id
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-  #       run: |
-  #         max_attempts=5  # Maximum number of attempts to retrieve the workflow run ID
-  #         attempt=0
-  #         workflow_list=""
+      - name: Get Workflow Run ID of maven.yml workflow
+        id: get_run_id
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          max_attempts=5  # Maximum number of attempts to retrieve the workflow run ID
+          attempt=0
+          workflow_list=""
 
-  #         while [ -z "$workflow_list" ] && [ $attempt -lt $max_attempts ]; do
-  #           echo "Attempt $(($attempt+1)) to retrieve workflow run ID"
-  #           workflow_list=$(gh run list --repo prashant-cloudbolt/qa-automation --workflow=maven.yml --branch=multi_tenant_stage --limit=1 --json databaseId)
+          while [ -z "$workflow_list" ] && [ $attempt -lt $max_attempts ]; do
+            echo "Attempt $(($attempt+1)) to retrieve workflow run ID"
+            workflow_list=$(gh run list --repo prashant-cloudbolt/qa-automation --workflow=maven.yml --branch=multi_tenant_stage --limit=1 --json databaseId)
             
-  #           if [ -z "$workflow_list" ]; then
-  #             echo "Workflow run ID not yet available. Retrying..."
-  #             attempt=$(($attempt + 1))
-  #             sleep 10  # Wait for a short time before retrying
-  #           else
-  #             echo "Workflow run ID retrieved successfully."
-  #           fi
-  #         done
+            if [ -z "$workflow_list" ]; then
+              echo "Workflow run ID not yet available. Retrying..."
+              attempt=$(($attempt + 1))
+              sleep 10  # Wait for a short time before retrying
+            else
+              echo "Workflow run ID retrieved successfully."
+            fi
+          done
 
-  #         if [ -z "$workflow_list" ]; then
-  #           echo "Failed to retrieve workflow run ID after $max_attempts attempts"
-  #           exit 1
-  #         fi
+          if [ -z "$workflow_list" ]; then
+            echo "Failed to retrieve workflow run ID after $max_attempts attempts"
+            exit 1
+          fi
 
-  #         run_id=$(echo "$workflow_list" | jq -r '.[0].databaseId')
-  #         echo "run_id=$run_id" >> $GITHUB_ENV
+          run_id=$(echo "$workflow_list" | jq -r '.[0].databaseId')
+          echo "run_id=$run_id" >> $GITHUB_ENV
 
 
-  #     - name: Check Target Workflow Status of maven.yml
-  #       id: check_status
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-  #       run: |
-  #         status=""
-  #         while [ "$status" != "completed" ]; do
-  #           status=$(gh run view ${{ env.run_id }} --repo prashant-cloudbolt/qa-automation --json status --jq '.status')
-  #           echo "Current status: $status"
-  #           if [ "$status" == "completed" ]; then
-  #             conclusion=$(gh run view ${{ env.run_id }} --repo prashant-cloudbolt/qa-automation --json conclusion --jq '.conclusion')
-  #             echo "Final conclusion: $conclusion"
-  #             if [ "$conclusion" != "success" ]; then
-  #               echo "Target workflow failed. Failing source workflow."
-  #               exit 1
-  #             fi
-  #           fi
-  #           sleep 15  # Increased sleep to reduce API calls
-  #         done
+      - name: Check Target Workflow Status of maven.yml
+        id: check_status
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          status=""
+          while [ "$status" != "completed" ]; do
+            status=$(gh run view ${{ env.run_id }} --repo prashant-cloudbolt/qa-automation --json status --jq '.status')
+            echo "Current status: $status"
+            if [ "$status" == "completed" ]; then
+              conclusion=$(gh run view ${{ env.run_id }} --repo prashant-cloudbolt/qa-automation --json conclusion --jq '.conclusion')
+              echo "Final conclusion: $conclusion"
+              if [ "$conclusion" != "success" ]; then
+                echo "Target workflow failed. Failing source workflow."
+                exit 1
+              fi
+            fi
+            sleep 15  # Increased sleep to reduce API calls
+          done
 
-  #     - name: Notify failure to Slack
-  #       uses: act10ns/slack@v2.0.0
-  #       if: ${{ failure() }}
-  #       env:
-  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }}
-  #       with:
-  #         status: ${{ job.status }}
-  #         message: |
-  #           :rotating_light: *QA Tests Failed*: API Deployment for CSMP-STAGE Environment
-  #           Repository: ${{ github.repository }}
-  #           Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      - name: Notify failure to Slack
+        uses: act10ns/slack@v2.0.0
+        if: ${{ failure() }}
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_NOTIFICATION_WEBHOOK }}
+        with:
+          status: ${{ job.status }}
+          message: |
+            :rotating_light: *QA Tests Failed*: API Deployment for CSMP-STAGE Environment
+            Repository: ${{ github.repository }}
+            Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
   codedeploy_rollback:
-    # if: ${{ always() && needs.qa-tests.result == 'failure' }}
-    # needs: qa-tests
+    if: ${{ always() && needs.qa-tests.result == 'failure' }} # Runs if `qa-tests` fails
+    needs: qa-tests
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -132,23 +128,15 @@ jobs:
           release_tag=$(gh release view $latest_release --json tagName -q ".tagName")
           echo "release_tag=$release_tag" >> $GITHUB_ENV
 
-          # commit_hash=$(git show $release_tag --pretty=format:"%H" --no-patch)
-          # echo "commit_hash=$commit_hash" >> $GITHUB_ENV
-
-      - name: Get Commit Hash from Tag2
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-        run: |
           commit_hash=$(gh api repos/${{ github.repository }}/git/ref/tags/$release_tag --jq '.object.sha')
           echo "commit_hash=$commit_hash" >> $GITHUB_ENV
 
-      - name: Display Results
+      - name: Display Results of Release, Tag, Hash
         run: |
           echo "Branch Suffix: ${{ env.branch_suffix }}"
-          echo "Latest Release: ${{ env.latest_release }}"
-          echo "Release Tag: ${{ env.release_tag }}"
-          echo "Commit Hash: ${{ env.commit_hash }}"
-
+          echo "Current Release: ${{ env.latest_release }}"
+          echo "Current Release Tag: ${{ env.release_tag }}"
+          echo "Commit Hash of Tag: ${{ env.commit_hash }}"
 
       # - name: Trigger Rollback of CodeDeploy
       #   env:
@@ -158,3 +146,39 @@ jobs:
       #     --ref=multi_tenant_stage \
       #     --repo prashant-cloudbolt/api \
       #     --field commit_hash=${{ env.LAST_COMMIT_SHA }}
+
+  release_api_stage:
+    if: ${{ github.ref == 'refs/heads/multi_tenant_stage' && always() && needs.qa-tests.result == 'success' }}  # Runs if `qa-tests` succeeds and branch is `multi_tenant_stage`
+    needs: [codedeploy]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: multi_tenant_stage
+
+      - name: Run release-version workflow
+        env:
+          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
+        run: |
+          gh workflow run release-version.yml \
+          --ref=multi_tenant_stage \
+          --repo prashant-cloudbolt/api
+
+  release_api_dev:
+    if: ${{ github.ref == 'refs/heads/multi_tenant_dev' && always() && needs.qa-tests.result == 'success' }}  # Runs if `qa-tests` succeeds and branch is `multi_tenant_dev`
+    needs: [codedeploy]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: multi_tenant_dev
+
+      - name: Run codedeploy-dev workflow
+        env:
+          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
+        run: |
+          gh workflow run release-version.yml \
+          --ref=multi_tenant_dev \
+          --repo prashant-cloudbolt/api
